fix

diff --git a/weather b/weather
--- a/weather
+++ b/weather
@@ -15,6 +15,7 @@
 function not_blank() {
   # if the first input is not empty and is not a space, return false
   # else return true
+
   if [[ -n "$1" ]] && [[ "$1" != " " ]]; then echo true
   else echo false; fi
 }
@@ -22,20 +23,21 @@ function not_blank() {
 function invalid_version() {
   # if the number does not match the regex, return true
   # else return false
+
   if ! [[ "$1" =~ ^[1-3]$ ]]; then echo true
   else echo false; fi
 }
 
 # the actual code
 
-if [[ $(not_blank "$1") ]]; then
-  if ! [[ "$1" =~ ^(v[1-3]\.)?wttr\.in.* ]]; then 
-    echo "error: invalid url '$1'"
-    exit 1
+# check if a custom url was given
+if $(not_blank "$1"); then
+  if ! [[ "$1" =~ ^(v[1-3]\.)?wttr\.in.*$ ]]; then
+    echo "error: url '$1' is not a valid url" >&2; exit 1
+  else
+    curl "$1"
+    exit 0
   fi
-  
-  curl "$1"
-  exit 0
 fi
 
 # read user input
@@ -43,7 +45,8 @@ read -rp "Which version of wttr.in should be used? (press enter for v1) " versio
 read -rp "Which place's weather should be shown? (press enter for current location) " place
 read -rp "What arguments should be added? (press enter for none) " arguments
 
-if [[ $(not_blank "$version") ]] && [[ $(invalid_version "$version") ]]; then
+# check if version is valid
+if $(not_blank "$version") && $(invalid_version "$version"); then
   echo "error: version '$version' is not a valid version" >&2; exit 1
 fi
 
@@ -51,12 +54,12 @@ fi
 url="v$version.wttr.in"
 
 # if a place is specified, use that place
-if [[ $(not_blank "$place") ]]; then
+if $(not_blank "$place"); then
   url+="/$place"
 fi
 
 # if arguments are specified, use those arguments
-if [[ $(not_blank "$arguments") ]]; then
+if $(not_blank "$arguments"); then
   url+="?$arguments"
 fi
 
