arg validation, custom url - cant put a invalid version now - can specify custom url by using "weather $url"

diff --git a/weather b/weather
--- a/weather
+++ b/weather
@@ -15,19 +15,37 @@
 function not_blank() {
   # if the first input is not empty and is not a space, return false
   # else return true
-  if [[ -n "$1" ]] && [[ "$1" != " " ]]; then
-    echo true
-  else
-    echo false
-  fi
+  if [[ -n "$1" ]] && [[ "$1" != " " ]]; then echo true
+  else echo false; fi
+}
+
+function invalid_version() {
+  # if the number does not match the regex, return true
+  # else return false
+  if ! [[ "$1" =~ ^[1-3]$ ]]; then echo true
+  else echo false; fi
 }
 
 # the actual code
+
+if [[ $(not_blank "$1") ]]; then
+  if ! [[ "$1" =~ ^(v[1-3]\.)?wttr\.in.* ]]; then 
+    echo "error: invalid url '$1'"
+    exit 1
+  fi
+  
+  curl "$1"
+  exit 0
+fi
 
 # read user input
 read -rp "Which version of wttr.in should be used? (press enter for v1) " version
 read -rp "Which place's weather should be shown? (press enter for current location) " place
 read -rp "What arguments should be added? (press enter for none) " arguments
+
+if [[ $(not_blank "$version") ]] && [[ $(invalid_version "$version") ]]; then
+  echo "error: version '$version' is not a valid version" >&2; exit 1
+fi
 
 # base url
 url="v$version.wttr.in"
